version: 2

registries:
  debitoor-npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.DEBITOOR_NPM_TOKEN }}
  sumup-npm-registry:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READ_PACKAGES_PAT }}

updates:
  # prod dependencies
  - package-ecosystem: npm
    directory: / # Location of package manifests
    registries:
      - debitoor-npm-registry
      - sumup-npm-registry
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 5
    labels:
      - dependencies
    allow:
      - dependency-type: production
    # dev dependencies
    - package-ecosystem: npm
    directory: / # Location of package manifests
    registries:
      - debitoor-npm-registry
      - sumup-npm-registry
    schedule:
      interval: monthly
    rebase-strategy: auto
    open-pull-requests-limit: 10
    labels:
      - dependencies
    allow:
      - dependency-type: development
